// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZGCDMDuTOkI-9r19CWBfFkKTcun3p4Jg',
    appId: '1:357235747702:web:91c340769a9304e8b62857',
    messagingSenderId: '357235747702',
    projectId: 'keuangan-a430f',
    authDomain: 'keuangan-a430f.firebaseapp.com',
    storageBucket: 'keuangan-a430f.appspot.com',
    measurementId: 'G-HEMQ5ZL5ZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKqoH9i3Lm-RCoj3C3bPHskNJoTbWewjM',
    appId: '1:357235747702:android:555905c2aaf222a1b62857',
    messagingSenderId: '357235747702',
    projectId: 'keuangan-a430f',
    storageBucket: 'keuangan-a430f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB65KXKSCrOotRh3nBgG3a9-iDhxX8ZpR0',
    appId: '1:357235747702:ios:190bc4c1bfb372feb62857',
    messagingSenderId: '357235747702',
    projectId: 'keuangan-a430f',
    storageBucket: 'keuangan-a430f.appspot.com',
    iosBundleId: 'com.example.appKeuangan',
  );
}
